1. [Install Java SDK 1.8 on RHEL 7 & CentOS 7](https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-install-java-sdk-1-8-on-rhel-7-centos-7.html)
2. [Install Java 8 on CentOS, RHEL and Fedora](https://tecadmin.net/install-java-8-on-centos-rhel-and-fedora/)
3. [Top 8 YUM ThirdParty Repositories for CentOS and RHEL](https://www.tecmint.com/yum-thirdparty-repositories-for-centos-rhel/)
4. [Red Hat Enterprise Linux FTP](http://ftp.redhat.com/pub/redhat/linux/enterprise/)
5. [Backup Crontabs for users in Linux](https://tecadmin.net/backup-crontabs-for-users-in-linux/)
